package datamodel.entities;

// default package
// Generated 4 may. 2021 12:40:59 by Hibernate Tools 5.4.30.Final

/**
 * Categorias generated by hbm2java
 */
public class Categorias implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;

	public Categorias() {
	}

	public Categorias(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
