package datamodel.entities;

// Generated 30 abr. 2021 17:56:21 by Hibernate Tools 5.4.30.Final

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Integer id;
	private String rol;

	public Roles() {
	}

	public Roles(String rol) {
		this.rol = rol;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

}
